function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = 999999999; // obj_globalstart
	global.__objectDepths[1] = 999999999; // obj_globalstart_escbutton
	global.__objectDepths[2] = 9999999; // obj_roomcontrol
	global.__objectDepths[3] = 999999999; // obj_rmcontrol_campaign
	global.__objectDepths[4] = 100; // obj_cam1
	global.__objectDepths[5] = 100; // obj_cam2
	global.__objectDepths[6] = -200; // obj_racestart
	global.__objectDepths[7] = 0; // obj_lapend
	global.__objectDepths[8] = 0; // object1008
	global.__objectDepths[9] = 0; // obj_lapend_nxtrom
	global.__objectDepths[10] = 0; // obj_lapend_rally
	global.__objectDepths[11] = 0; // obj_powerupbox
	global.__objectDepths[12] = 0; // obj_magicdrop
	global.__objectDepths[13] = 0; // obj_wincam_pos
	global.__objectDepths[14] = 0; // obj_falltraparea_hor
	global.__objectDepths[15] = 0; // obj_fall_traparea_vert
	global.__objectDepths[16] = 0; // obj_savepoint
	global.__objectDepths[17] = 0; // obj_jumppad
	global.__objectDepths[18] = 0; // obj_portal_nxtrom
	global.__objectDepths[19] = 0; // obj_portal_prevrom
	global.__objectDepths[20] = 999999999; // obj_start_sp_pl1
	global.__objectDepths[21] = 999999999; // obj_start_sp_pl2
	global.__objectDepths[22] = 999999999; // obj_start_sp_pl3
	global.__objectDepths[23] = 999999999; // obj_start_sp_pl4
	global.__objectDepths[24] = 999999999; // obj_start_sp_bot5
	global.__objectDepths[25] = 999999999; // obj_start_sp_bot6
	global.__objectDepths[26] = 999999999; // obj_start_custom
	global.__objectDepths[27] = 0; // obj_podium_pos1
	global.__objectDepths[28] = 0; // obj_podium_pos2
	global.__objectDepths[29] = 0; // obj_podium_pos3
	global.__objectDepths[30] = 0; // obj_podium_pos4
	global.__objectDepths[31] = 0; // obj_podium_pos5
	global.__objectDepths[32] = 0; // obj_podium_pos6
	global.__objectDepths[33] = 0; // obj_portal_battle_froggitduo
	global.__objectDepths[34] = 0; // obj_portal_battle_vegeduo
	global.__objectDepths[35] = 0; // obj_portal_battle_vegefrog
	global.__objectDepths[36] = 0; // obj_portal_battle_ruinsmobs
	global.__objectDepths[37] = 0; // obj_portal_battle_snowrally
	global.__objectDepths[38] = 0; // obj_portal_battle_icecapduo
	global.__objectDepths[39] = 0; // obj_portal_battle_snowmobs
	global.__objectDepths[40] = 0; // obj_portal_battle_mk
	global.__objectDepths[41] = 0; // obj_portal_floweyrace
	global.__objectDepths[42] = 0; // obj_portal_blookrace
	global.__objectDepths[43] = 0; // obj_portal_pretorielrace
	global.__objectDepths[44] = 0; // obj_portal_torielrace
	global.__objectDepths[45] = 0; // obj_portal_pretoriel_toruins
	global.__objectDepths[46] = 0; // obj_portal_fake
	global.__objectDepths[47] = -10; // obj_kart_sans
	global.__objectDepths[48] = -10; // obj_kart_papyrus
	global.__objectDepths[49] = -10; // obj_kart_undyne
	global.__objectDepths[50] = -10; // obj_kart_alphys
	global.__objectDepths[51] = -10; // obj_kart_mettaton
	global.__objectDepths[52] = -10; // obj_kart_mttex
	global.__objectDepths[53] = -10; // obj_kart_frisk
	global.__objectDepths[54] = -10; // obj_kart_blook
	global.__objectDepths[55] = -10; // obj_kart_asgore
	global.__objectDepths[56] = -10; // obj_kart_toriel
	global.__objectDepths[57] = -10; // obj_kart_chara
	global.__objectDepths[58] = -10; // obj_kart_asriel
	global.__objectDepths[59] = -10; // obj_kart_gaster
	global.__objectDepths[60] = -10; // obj_kart_flowey
	global.__objectDepths[61] = -10; // obj_kart_muffet
	global.__objectDepths[62] = -10; // obj_kart_maddummy
	global.__objectDepths[63] = -10; // obj_kart_bpants
	global.__objectDepths[64] = -10; // obj_kart_grillby
	global.__objectDepths[65] = -10; // obj_kart_mk
	global.__objectDepths[66] = -10; // obj_kart_tem
	global.__objectDepths[67] = -10; // obj_kart_doggo
	global.__objectDepths[68] = -10; // obj_kart_toby
	global.__objectDepths[69] = -10; // obj_kart_froggit1
	global.__objectDepths[70] = -10; // obj_kart_froggit2
	global.__objectDepths[71] = -10; // obj_kart_vegetoid1
	global.__objectDepths[72] = -10; // obj_kart_vegetoid2
	global.__objectDepths[73] = -10; // obj_kart_snowdrake1
	global.__objectDepths[74] = -10; // obj_kart_snowdrake2
	global.__objectDepths[75] = -10; // obj_kart_icecap1
	global.__objectDepths[76] = -10; // obj_kart_icecap2
	global.__objectDepths[77] = 0; // obj_npc_hfrisk
	global.__objectDepths[78] = 0; // obj_playcpmnbutton
	global.__objectDepths[79] = 0; // obj_playfreebutton
	global.__objectDepths[80] = 0; // obj_menubutton
	global.__objectDepths[81] = 0; // obj_optionsbutton
	global.__objectDepths[82] = 0; // obj_achievebutton
	global.__objectDepths[83] = 0; // obj_exitbutton
	global.__objectDepths[84] = 0; // obj_howmanyplayersbutton
	global.__objectDepths[85] = 0; // obj_botstriggerbutton
	global.__objectDepths[86] = 0; // obj_botsonlybutton
	global.__objectDepths[87] = 0; // obj_readybutton
	global.__objectDepths[88] = 0; // obj_resetbutton
	global.__objectDepths[89] = 0; // obj_laplimitbutton
	global.__objectDepths[90] = 0; // obj_options_renderdist
	global.__objectDepths[91] = 0; // obj_options_musicvol
	global.__objectDepths[92] = 0; // obj_options_controlinput
	global.__objectDepths[93] = 0; // obj_options_controls
	global.__objectDepths[94] = 0; // obj_options_pl1binds_kb
	global.__objectDepths[95] = 0; // obj_options_pl2binds_kb
	global.__objectDepths[96] = 0; // obj_options_pl1_jk
	global.__objectDepths[97] = 0; // obj_options_pl2_jk
	global.__objectDepths[98] = 0; // obj_slct_title
	global.__objectDepths[99] = 0; // obj_slct_papyrus
	global.__objectDepths[100] = 0; // obj_slct_sans
	global.__objectDepths[101] = 0; // obj_slct_undyne
	global.__objectDepths[102] = 0; // obj_slct_alphys
	global.__objectDepths[103] = 0; // obj_slct_frisk
	global.__objectDepths[104] = 0; // obj_slct_mettaton
	global.__objectDepths[105] = 0; // obj_slct_mttex
	global.__objectDepths[106] = 0; // obj_slct_toriel
	global.__objectDepths[107] = 0; // obj_slct_asgore
	global.__objectDepths[108] = 0; // obj_slct_asriel
	global.__objectDepths[109] = 0; // obj_slct_gaster
	global.__objectDepths[110] = 0; // obj_slct_us_sans
	global.__objectDepths[111] = 0; // obj_slct_uf_papy
	global.__objectDepths[112] = 0; // obj_slct_ss_chara
	global.__objectDepths[113] = 0; // obj_slct_flowey
	global.__objectDepths[114] = 0; // obj_slct_napstablook
	global.__objectDepths[115] = 0; // obj_slct_muffet
	global.__objectDepths[116] = 0; // obj_slct_maddummy
	global.__objectDepths[117] = 0; // obj_slct_bpants
	global.__objectDepths[118] = 0; // obj_slct_mk
	global.__objectDepths[119] = 0; // obj_slct_tem
	global.__objectDepths[120] = 0; // obj_slct_grillby
	global.__objectDepths[121] = 0; // obj_slct_toby
	global.__objectDepths[122] = 0; // obj_slct_doggo
	global.__objectDepths[123] = 0; // obj_slct_nochar
	global.__objectDepths[124] = 0; // obj_slctkart_preview
	global.__objectDepths[125] = 0; // obj_achieve_floweysouls
	global.__objectDepths[126] = 0; // obj_achieve_corefall
	global.__objectDepths[127] = 0; // obj_achieve_papyblaster
	global.__objectDepths[128] = 0; // obj_achieve_secretcodewall
	global.__objectDepths[129] = 0; // obj_achieve_unlockdog
	global.__objectDepths[130] = 10; // obj_intro
	global.__objectDepths[131] = 0; // obj_intro_frisk
	global.__objectDepths[132] = 0; // obj_intro_undyne
	global.__objectDepths[133] = 0; // obj_intro_gaster
	global.__objectDepths[134] = 0; // obj_intro_title
	global.__objectDepths[135] = 0; // obj_intro_voidfx
	global.__objectDepths[136] = 0; // obj_menuchar_frisk
	global.__objectDepths[137] = 0; // obj_menuchar_tori
	global.__objectDepths[138] = 1; // obj_menuchar_blook
	global.__objectDepths[139] = 1; // obj_menuchar_vegetoid
	global.__objectDepths[140] = 1; // obj_menuchar_froggit
	global.__objectDepths[141] = 1; // obj_menuchar_gaster
	global.__objectDepths[142] = 0; // obj_menuchar_sans
	global.__objectDepths[143] = 0; // obj_menuchar_papyrus
	global.__objectDepths[144] = 0; // obj_slctchar_ut
	global.__objectDepths[145] = 0; // obj_slctchar_ut_rm1
	global.__objectDepths[146] = 0; // obj_slctchar_ut_rm2
	global.__objectDepths[147] = 0; // obj_slctchar_au
	global.__objectDepths[148] = 0; // obj_lvl_title
	global.__objectDepths[149] = 0; // obj_lvl_ruins
	global.__objectDepths[150] = 0; // obj_lvl_christmas
	global.__objectDepths[151] = 0; // obj_lvl_snowdin_forest
	global.__objectDepths[152] = 0; // obj_lvl_waterfall
	global.__objectDepths[153] = 0; // obj_lvl_core
	global.__objectDepths[154] = 0; // obj_lvl_hotlands
	global.__objectDepths[155] = 0; // obj_lvl_boss_toriel
	global.__objectDepths[156] = 0; // obj_lvl_boss_blook
	global.__objectDepths[157] = 0; // obj_lvl_boss_papyrus
	global.__objectDepths[158] = 0; // obj_newtitle
	global.__objectDepths[159] = 1; // obj_newmenu
	global.__objectDepths[160] = 0; // obj_freerace_vsboss
	global.__objectDepths[161] = 0; // obj_freerace_normalcircuit
	global.__objectDepths[162] = 999999999; // obj_terspawn_snowdinoverworld
	global.__objectDepths[163] = 999999999; // obj_terspawn_snowrally
	global.__objectDepths[164] = 999999999; // obj_terspawn_snowdinmisc
	global.__objectDepths[165] = 999999999; // obj_terrain_snowdinoverworld
	global.__objectDepths[166] = 999999999; // obj_terrain_snowrally
	global.__objectDepths[167] = 999999999; // obj_terrain_snowdinmisc
	global.__objectDepths[168] = -1; // obj_wall_snowdin_hor
	global.__objectDepths[169] = -1; // obj_wall_cliff_horizontal
	global.__objectDepths[170] = -1; // obj_wall_forest_horizontal
	global.__objectDepths[171] = -1; // obj_wall_snowdin_vert
	global.__objectDepths[172] = -1; // obj_wall_cliff_vertical
	global.__objectDepths[173] = -1; // obj_wall_forest_vertical
	global.__objectDepths[174] = -1; // obj_snowcliff_hor
	global.__objectDepths[175] = -1; // obj_snowcliff_vert
	global.__objectDepths[176] = 0; // obj_floor_snowcliff
	global.__objectDepths[177] = 0; // obj_floor_snowdin
	global.__objectDepths[178] = 0; // obj_floor_lowsnow
	global.__objectDepths[179] = 0; // obj_floor_snow
	global.__objectDepths[180] = 0; // obj_snowtile_up
	global.__objectDepths[181] = 0; // obj_snowtilesmallcornersw
	global.__objectDepths[182] = 0; // obj_snowtilelongcornersw
	global.__objectDepths[183] = 0; // obj_snowtilelongcornernw
	global.__objectDepths[184] = 0; // obj_snowtilelongcornerne
	global.__objectDepths[185] = 0; // obj_snowtilelongcornerse
	global.__objectDepths[186] = 0; // obj_snowtilesmallcornernw
	global.__objectDepths[187] = 0; // obj_snowtilesmallcornerne
	global.__objectDepths[188] = 0; // obj_snowtilesmallcornerse
	global.__objectDepths[189] = 0; // obj_snowtile_down
	global.__objectDepths[190] = 0; // obj_snowtile_left
	global.__objectDepths[191] = 0; // obj_snowtile_right
	global.__objectDepths[192] = 0; // obj_floor_forestsnow
	global.__objectDepths[193] = 0; // obj_bridge_horizontal1
	global.__objectDepths[194] = 0; // obj_bridge_horizontal
	global.__objectDepths[195] = 0; // obj_bridge_vertical
	global.__objectDepths[196] = 0; // obj_bridge_horizontal2
	global.__objectDepths[197] = 0; // obj_bridge_vertical1
	global.__objectDepths[198] = 0; // obj_bridge_vertical2
	global.__objectDepths[199] = 0; // obj_floor_ice
	global.__objectDepths[200] = 0; // obj_poff
	global.__objectDepths[201] = 0; // obj_poff_cliff
	global.__objectDepths[202] = 0; // obj_tree
	global.__objectDepths[203] = 0; // obj_tree_cliff
	global.__objectDepths[204] = 0; // obj_doghouse
	global.__objectDepths[205] = 0; // obj_bars
	global.__objectDepths[206] = 0; // obj_npc_politicsbear
	global.__objectDepths[207] = 0; // obj_npc_grillby
	global.__objectDepths[208] = 0; // obj_convenientlamp
	global.__objectDepths[209] = 0; // obj_npc_snowdinlowriders
	global.__objectDepths[210] = -1; // obj_wall_snowbridge_hor
	global.__objectDepths[211] = -1; // obj_wall_snowbridge_vert
	global.__objectDepths[212] = 0; // obj_shop_snowdin
	global.__objectDepths[213] = 0; // obj_inn_snowdin
	global.__objectDepths[214] = 0; // obj_midshop_snowdin
	global.__objectDepths[215] = 0; // obj_librarby
	global.__objectDepths[216] = 0; // obj_grillbys
	global.__objectDepths[217] = 0; // obj_house_snowdin
	global.__objectDepths[218] = 0; // obj_papshouse
	global.__objectDepths[219] = -1; // obj_wall_ruins_hor
	global.__objectDepths[220] = -1; // obj_wall_ruins_vert
	global.__objectDepths[221] = -1; // obj_wall2_ruins_hor
	global.__objectDepths[222] = -1; // obj_wall2_ruins_vert
	global.__objectDepths[223] = 0; // obj_floor_ruins
	global.__objectDepths[224] = 0; // obj_floor_black
	global.__objectDepths[225] = 0; // obj_floor_leaves_ruins
	global.__objectDepths[226] = 0; // obj_floor_vines_ruins
	global.__objectDepths[227] = 0; // obj_floor_trap
	global.__objectDepths[228] = -1; // obj_wall_home_hor
	global.__objectDepths[229] = -1; // obj_wall_home_vert
	global.__objectDepths[230] = 0; // obj_floor_home
	global.__objectDepths[231] = 0; // obj_pillar_ruins
	global.__objectDepths[232] = 0; // obj_home_lamp
	global.__objectDepths[233] = 0; // obj_ruins_tree
	global.__objectDepths[234] = 0; // obj_trap_rock
	global.__objectDepths[235] = 0; // obj_npc_dummy
	global.__objectDepths[236] = 0; // obj_npc_maddummy
	global.__objectDepths[237] = 0; // obj_npc_vegetoid
	global.__objectDepths[238] = 0; // obj_npc_napstablook
	global.__objectDepths[239] = 0; // obj_npc_froggit
	global.__objectDepths[240] = 0; // obj_talkingrock
	global.__objectDepths[241] = -1; // obj_wall_ruins_fake_hor
	global.__objectDepths[242] = -1; // obj_wall_ruins_fake_vert
	global.__objectDepths[243] = -1; // obj_wall_black_hor
	global.__objectDepths[244] = -1; // obj_black_smallwall_hor
	global.__objectDepths[245] = -1; // obj_black_filler
	global.__objectDepths[246] = -1; // obj_wall_black_vert
	global.__objectDepths[247] = -1; // obj_black_smallwall_vert
	global.__objectDepths[248] = 0; // obj_ruinsgate_empty
	global.__objectDepths[249] = 0; // obj_ruinsgate
	global.__objectDepths[250] = 0; // obj_floor_ruins_waterfloor
	global.__objectDepths[251] = 10; // obj_ruins_firstroom
	global.__objectDepths[252] = -1; // obj_ruins_homewalls_vert
	global.__objectDepths[253] = -1; // obj_codewall_hor
	global.__objectDepths[254] = -1; // obj_wall_wfall_hor
	global.__objectDepths[255] = -1; // obj_wall_wfall_vert
	global.__objectDepths[256] = -1; // obj_wall_wfall2_hor
	global.__objectDepths[257] = -1; // obj_wall_wfall2_vert
	global.__objectDepths[258] = -1; // obj_wall_wfall_water_hor
	global.__objectDepths[259] = -1; // obj_wall_wfall_water_vert
	global.__objectDepths[260] = 0; // obj_floor_wfall
	global.__objectDepths[261] = 0; // obj_floor_wfall_grass
	global.__objectDepths[262] = 0; // obj_floor_wfall_waterfloor
	global.__objectDepths[263] = 0; // obj_floor_bridge
	global.__objectDepths[264] = 0; // obj_floor_wfallcliff
	global.__objectDepths[265] = -1; // obj_wfall_cliff_hor
	global.__objectDepths[266] = -1; // obj_wfall_cliff_vert
	global.__objectDepths[267] = 0; // obj_pillar_waterfall
	global.__objectDepths[268] = 0; // obj_prop_bigshroom_wfall
	global.__objectDepths[269] = 0; // obj_prop_mushroom
	global.__objectDepths[270] = 0; // obj_prop_lamp
	global.__objectDepths[271] = 0; // obj_watergate
	global.__objectDepths[272] = 0; // obj_terrain_hotlava
	global.__objectDepths[273] = -1; // obj_hotcliff_hor
	global.__objectDepths[274] = -1; // obj_hotcliff_vert
	global.__objectDepths[275] = 0; // obj_hotlands_floor
	global.__objectDepths[276] = 0; // obj_hotlands_floorpipe_h1
	global.__objectDepths[277] = 0; // obj_hotlands_floorpipe_h2
	global.__objectDepths[278] = 0; // obj_hotlands_floorpipe_v1
	global.__objectDepths[279] = 0; // obj_hotlands_floorpipe_v2
	global.__objectDepths[280] = 0; // obj_hotlands_floorpipe_v3
	global.__objectDepths[281] = 0; // obj_hotlands_pipe
	global.__objectDepths[282] = 0; // obj_floor_corehole
	global.__objectDepths[283] = 0; // obj_floor_core
	global.__objectDepths[284] = 0; // obj_floor_corebridge
	global.__objectDepths[285] = 0; // obj_floor_mttshow
	global.__objectDepths[286] = -1; // obj_wall_core_hor
	global.__objectDepths[287] = -1; // obj_wall_core_vert
	global.__objectDepths[288] = -1; // obj_wall_mttshow_hor
	global.__objectDepths[289] = -1; // obj_wall_mttshow_vert
	global.__objectDepths[290] = -1; // obj_wall_corehole_hor
	global.__objectDepths[291] = -1; // obj_wall_corehole_vert
	global.__objectDepths[292] = 0; // obj_mttshow_gate
	global.__objectDepths[293] = -1; // obj_wall_corebridge_hor
	global.__objectDepths[294] = -1; // obj_wall_corebrige_vert
	global.__objectDepths[295] = 0; // obj_npc_rg01
	global.__objectDepths[296] = 0; // obj_npc_rg02
	global.__objectDepths[297] = 0; // obj_npc_regnpc
	global.__objectDepths[298] = 0; // obj_npc_tsunderplane
	global.__objectDepths[299] = 0; // obj_npc_darkman
	global.__objectDepths[300] = 0; // obj_npc_vulkin
	global.__objectDepths[301] = 0; // obj_npc_harpy
	global.__objectDepths[302] = 0; // obj_npc_heatsf
	global.__objectDepths[303] = 0; // obj_npc_pyrope
	global.__objectDepths[304] = 0; // obj_firepit
	global.__objectDepths[305] = 0; // obj_tree_christmas
	global.__objectDepths[306] = 0; // obj_cane_christmas
	global.__objectDepths[307] = 0; // obj_present_red
	global.__objectDepths[308] = 0; // obj_present_blue
	global.__objectDepths[309] = 0; // obj_present_maroon
	global.__objectDepths[310] = 0; // obj_snowman_sux
	global.__objectDepths[311] = 0; // obj_snowman_luke
	global.__objectDepths[312] = 0; // obj_snowman_ricky
	global.__objectDepths[313] = 0; // obj_snowman_funny
	global.__objectDepths[314] = 0; // obj_snowman_gravy
	global.__objectDepths[315] = 0; // obj_snowman_luigi
	global.__objectDepths[316] = 0; // obj_snowman_muffin
	global.__objectDepths[317] = 0; // obj_snowman_crash
	global.__objectDepths[318] = 0; // obj_snowman_lucas
	global.__objectDepths[319] = 0; // obj_snowman_brawl
	global.__objectDepths[320] = 0; // obj_snowman_seth
	global.__objectDepths[321] = 0; // obj_tem_christmas
	global.__objectDepths[322] = 0; // obj_magic_christmas
	global.__objectDepths[323] = 0; // obj_powerup_christmas
	global.__objectDepths[324] = -1; // obj_christlights_vert
	global.__objectDepths[325] = -1; // obj_christlights_hor
	global.__objectDepths[326] = 0; // obj_newhome_floor
	global.__objectDepths[327] = -1; // obj_newhome_wall_hor
	global.__objectDepths[328] = -1; // obj_newhome_wall_vert
	global.__objectDepths[329] = -1; // obj_newhome_homewall_hor
	global.__objectDepths[330] = -1; // obj_newhome_homewall_vert
	global.__objectDepths[331] = 0; // obj_newhome_homefloor
	global.__objectDepths[332] = 0; // obj_newhome_lamp
	global.__objectDepths[333] = 0; // obj_newhome_throne
	global.__objectDepths[334] = 0; // obj_newhome_thronet
	global.__objectDepths[335] = 0; // obj_newhome_floor_vines
	global.__objectDepths[336] = -1; // obj_newhome_wall_fake_hor
	global.__objectDepths[337] = -1; // obj_newhome_wall_fake_vert
	global.__objectDepths[338] = 0; // obj_goldenflowers
	global.__objectDepths[339] = 0; // obj_newhome_vines_floor
	global.__objectDepths[340] = 0; // obj_judge_pillar
	global.__objectDepths[341] = 0; // obj_judge_floor1
	global.__objectDepths[342] = 0; // obj_judge_floor2
	global.__objectDepths[343] = 0; // obj_judge_floor1_dark
	global.__objectDepths[344] = 0; // obj_judge_floor2_dark
	global.__objectDepths[345] = 0; // obj_judge_floor1_light
	global.__objectDepths[346] = 0; // obj_judge_floor2_light
	global.__objectDepths[347] = -1; // obj_judge_window_1_hor
	global.__objectDepths[348] = -1; // obj_judge_window_1_vert
	global.__objectDepths[349] = -1; // obj_judge_window_2_hor
	global.__objectDepths[350] = -1; // obj_judge_window_2_vert
	global.__objectDepths[351] = -1; // obj_judge_wall_hor
	global.__objectDepths[352] = -1; // obj_judge_wall_vert
	global.__objectDepths[353] = -1; // obj_judge_wall_dark_hor
	global.__objectDepths[354] = -1; // obj_judge_wall_dark_vert
	global.__objectDepths[355] = 0; // obj_col_basic
	global.__objectDepths[356] = 0; // obj_kart_basic
	global.__objectDepths[357] = 0; // obj_floor_draw_basic
	global.__objectDepths[358] = 0; // obj_floor_draw_animated_basic
	global.__objectDepths[359] = 0; // obj_wall_draw_basic
	global.__objectDepths[360] = 0; // obj_wall_draw_animated_basic
	global.__objectDepths[361] = 0; // obj_wall_draw_nocol
	global.__objectDepths[362] = 0; // obj_podium_basic
	global.__objectDepths[363] = 0; // obj_powerup_basic
	global.__objectDepths[364] = 0; // obj_tpfx
	global.__objectDepths[365] = 0; // obj_bonefx
	global.__objectDepths[366] = 0; // obj_spearfx
	global.__objectDepths[367] = 0; // obj_bulletfx
	global.__objectDepths[368] = 0; // obj_bulletfx_big
	global.__objectDepths[369] = 0; // obj_grassfx
	global.__objectDepths[370] = 0; // obj_racefx
	global.__objectDepths[371] = 0; // obj_snowfloorfx
	global.__objectDepths[372] = 0; // obj_waterfloorfx
	global.__objectDepths[373] = 0; // obj_bynaryfallfx
	global.__objectDepths[374] = 0; // obj_kaster_hands
	global.__objectDepths[375] = -200; // obj_hud1
	global.__objectDepths[376] = -250; // obj_hud2
	global.__objectDepths[377] = -250; // obj_hud_racend
	global.__objectDepths[378] = -250; // obj_hud_black
	global.__objectDepths[379] = -250; // obj_hud_quit
	global.__objectDepths[380] = -250; // obj_hud_save
	global.__objectDepths[381] = -250; // obj_hud_battle
	global.__objectDepths[382] = -250; // obj_hud_achievement
	global.__objectDepths[383] = -200; // obj_hud_campaign
	global.__objectDepths[384] = -250; // obj_hud_quit_campaign
	global.__objectDepths[385] = 0; // obj_hud_pause
	global.__objectDepths[386] = 0; // obj_powerup_spike
	global.__objectDepths[387] = 0; // obj_powerup_tilespear
	global.__objectDepths[388] = 0; // obj_powerup_tileweb
	global.__objectDepths[389] = 0; // obj_powerup_bone
	global.__objectDepths[390] = 0; // obj_powerup_asrielstar
	global.__objectDepths[391] = 0; // obj_powerup_asrielbullet
	global.__objectDepths[392] = 0; // obj_powerup_fireball
	global.__objectDepths[393] = 0; // obj_powerup_bone_blue
	global.__objectDepths[394] = 0; // obj_powerup_knife
	global.__objectDepths[395] = 0; // obj_powerup_cotton
	global.__objectDepths[396] = 0; // obj_powerup_spear
	global.__objectDepths[397] = 0; // obj_powerup_pellet
	global.__objectDepths[398] = 0; // obj_powerup_shock
	global.__objectDepths[399] = 0; // obj_powerup_gb
	global.__objectDepths[400] = 0; // obj_powerup_mttsentry
	global.__objectDepths[401] = 0; // obj_powerup_tear
	global.__objectDepths[402] = 0; // obj_powerup_ylwbullet
	global.__objectDepths[403] = 0; // obj_gblast
	global.__objectDepths[404] = 0; // obj_trap_spikes
	global.__objectDepths[405] = 0; // obj_flowey_intro
	global.__objectDepths[406] = 0; // obj_timeline_menu
	global.__objectDepths[407] = 0; // obj_menu_friskart
	global.__objectDepths[408] = 0; // obj_menu_papykart
	global.__objectDepths[409] = 0; // obj_menu_dreemurkart
	global.__objectDepths[410] = 0; // obj_menu_badtime
	global.__objectDepths[411] = 0; // obj_pellet_cutscene
	global.__objectDepths[412] = 0; // obj_fireball_cutscene
	global.__objectDepths[413] = 1; // obj_binarycutscene
	global.__objectDepths[414] = 0; // obj_hfrisk_laughface
	global.__objectDepths[415] = -200; // obj_dlg_errormsg
	global.__objectDepths[416] = -200; // obj_dlg_introflowey
	global.__objectDepths[417] = -200; // obj_dlg_introflowey2
	global.__objectDepths[418] = -200; // obj_dlg_floweyracetut
	global.__objectDepths[419] = -200; // obj_dlg_floweybossintro
	global.__objectDepths[420] = -200; // obj_dlg_floweyrace_friskwins
	global.__objectDepths[421] = -200; // obj_dlg_floweyrace_friskloses
	global.__objectDepths[422] = -200; // obj_dlg_floweypellets_intro
	global.__objectDepths[423] = -200; // obj_dlg_tori_intro
	global.__objectDepths[424] = -200; // obj_dlg_floweyjudgement
	global.__objectDepths[425] = -200; // obj_dlg_floweyjudgement_end
	global.__objectDepths[426] = -200; // obj_dlg_introhakd
	global.__objectDepths[427] = -200; // obj_dlg_floweyintro_hakd
	global.__objectDepths[428] = -200; // obj_dlg_hfriskintro
	global.__objectDepths[429] = -200; // obj_dlg_ruins_blookyrace1
	global.__objectDepths[430] = -200; // obj_dlg_ruins_blookyrace2
	global.__objectDepths[431] = -200; // obj_dlg_froggit_torielalert
	global.__objectDepths[432] = -200; // obj_froggit_mobracealert
	global.__objectDepths[433] = -200; // obj_dlg_blookbossintro
	global.__objectDepths[434] = -200; // obj_dlg_blookwins
	global.__objectDepths[435] = -200; // obj_dlg_blookloses
	global.__objectDepths[436] = -200; // obj_dlg_vgtoid_rockalert
	global.__objectDepths[437] = -200; // obj_dlg_sorryrock
	global.__objectDepths[438] = -200; // obj_dlg_hiya
	global.__objectDepths[439] = -200; // obj_dlg_torielpreintro
	global.__objectDepths[440] = -200; // obj_dlg_torielbossintro
	global.__objectDepths[441] = -200; // obj_dlg_torielwins
	global.__objectDepths[442] = -200; // obj_dlg_torielloses
	global.__objectDepths[443] = -200; // obj_dlg_torielruinsexit
	global.__objectDepths[444] = -200; // obj_dlg_racestart
	global.__objectDepths[445] = -200; // obj_dlg_racewin
	global.__objectDepths[446] = -200; // obj_dlg_racelose
	global.__objectDepths[447] = -200; // obj_dlg_meetsans
	global.__objectDepths[448] = -200; // obj_dlg_meetsansalt
	global.__objectDepths[449] = -200; // obj_dlg_sansrevealed
	global.__objectDepths[450] = -200; // obj_dlg_sanspap1
	global.__objectDepths[451] = -200; // obj_dlg_sansfrisk1
	global.__objectDepths[452] = -200; // obj_dlg_floweypostruins
	global.__objectDepths[453] = -200; // obj_dlg_snowdinlowriders_1
	global.__objectDepths[454] = -200; // obj_dlg_snowdinlowriders_2
	global.__objectDepths[455] = -200; // obj_dlg_snowdinlowriders_3
	global.__objectDepths[456] = -200; // obj_dlg_hfrisk_snowsecret
	global.__objectDepths[457] = -200; // obj_dlg_whatwasthat
	global.__objectDepths[458] = -200; // obj_dlg_threedots
	global.__objectDepths[459] = -200; // obj_dlg_mk_racestart
	global.__objectDepths[460] = -200; // obj_dlg_raceicecapduo
	global.__objectDepths[461] = -200; // obj_dlg_racemk
	global.__objectDepths[462] = -200; // obj_dlg_raceahead
	global.__objectDepths[463] = -200; // obj_dlg_younohere
	global.__objectDepths[464] = -200; // obj_dlg_doghouse
	global.__objectDepths[465] = -200; // obj_dlg_alwaysfacing
	global.__objectDepths[466] = -200; // obj_dlg_papybossintro
	global.__objectDepths[467] = -200; // obj_dlg_papywins
	global.__objectDepths[468] = -200; // obj_dlg_papyloses
	global.__objectDepths[469] = -200; // obj_dlg_papybridge
	global.__objectDepths[470] = -200; // obj_dlg_papybridge_completed
	global.__objectDepths[471] = -200; // obj_dlg_papygate
	global.__objectDepths[472] = -200; // obj_dlg_sanspapracetip
	global.__objectDepths[473] = 0; // obj_trigger_talkwithchar
	global.__objectDepths[474] = -20; // obj_trigger_floweyintrodialog
	global.__objectDepths[475] = -20; // obj_trigger_floweyracetut
	global.__objectDepths[476] = -20; // obj_trigger_floweypellets_intro
	global.__objectDepths[477] = -20; // obj_trigger_tori_intro
	global.__objectDepths[478] = 0; // obj_trigger_rmhacking
	global.__objectDepths[479] = -20; // obj_trigger_floweyjudgement
	global.__objectDepths[480] = 0; // obj_trigger_floweyjudgement_end
	global.__objectDepths[481] = 0; // obj_trigger_floweysink
	global.__objectDepths[482] = 0; // obj_trigger_introhakd
	global.__objectDepths[483] = 0; // obj_trigger_floweyintro_hakd
	global.__objectDepths[484] = 0; // obj_trigger_hfriskintro
	global.__objectDepths[485] = -20; // obj_trigger_floweypostruins
	global.__objectDepths[486] = 0; // obj_trigger_meetsans
	global.__objectDepths[487] = 0; // obj_trigger_sanspap1
	global.__objectDepths[488] = 0; // obj_trigger_sanstp
	global.__objectDepths[489] = 0; // obj_trigger_sansfrisk1
	global.__objectDepths[490] = 0; // obj_trigger_papbridge
	global.__objectDepths[491] = 0; // obj_trigger_papbridge_completed
	global.__objectDepths[492] = 0; // obj_trigger_papygate
	global.__objectDepths[493] = -20; // obj_trigger_froggitduoend
	global.__objectDepths[494] = -20; // obj_trigger_vegeduoend
	global.__objectDepths[495] = -20; // obj_trigger_vegefrogend
	global.__objectDepths[496] = -20; // obj_trigger_ruinsmobsend
	global.__objectDepths[497] = -20; // obj_trigger_snowdrakerallyend
	global.__objectDepths[498] = -20; // obj_trigger_icecapduo
	global.__objectDepths[499] = -20; // obj_trigger_snowmobs
	global.__objectDepths[500] = -20; // obj_trigger_mk
	global.__objectDepths[501] = 0; // obj_trigger_floweybossintro
	global.__objectDepths[502] = -20; // obj_trigger_floweyracefinale
	global.__objectDepths[503] = 0; // obj_trigger_blookbossintro
	global.__objectDepths[504] = -20; // obj_trigger_blookfinale
	global.__objectDepths[505] = 0; // obj_trigger_torielpreintro
	global.__objectDepths[506] = 0; // obj_trigger_torielbossintro
	global.__objectDepths[507] = -20; // obj_trigger_torielfinale
	global.__objectDepths[508] = 0; // obj_trigger_torielruinsexit
	global.__objectDepths[509] = 0; // obj_trigger_papyrusbossintro
	global.__objectDepths[510] = -20; // obj_trigger_papyrusbossfinale
	global.__objectDepths[511] = 0; // obj_tobdog
	global.__objectDepths[512] = 0; // obj_dokdog
	global.__objectDepths[513] = 0; // obj_bynary_spawner
	global.__objectDepths[514] = 0; // obj_cmpn_indev
	global.__objectDepths[515] = 0; // obj_demoend
	global.__objectDepths[516] = 0; // obj_fadetocampaign
	global.__objectDepths[517] = 0; // obj_fadetosnowdin
	global.__objectDepths[518] = 0; // obj_fadetodemoend
	global.__objectDepths[519] = -99999; // obj_mouse_joystick
	global.__objectDepths[520] = 0; // obj_gotolvl_freerace
	global.__objectDepths[521] = 0; // obj_gotolvl_campaign
	global.__objectDepths[522] = -200; // obj_writer
	global.__objectDepths[523] = 0; // obj_escbutton
	global.__objectDepths[524] = 0; // obj_escbutton_3d
	global.__objectDepths[525] = 0; // obj_escbutton_3dcampaign
	global.__objectDepths[526] = 0; // obj_achievement_tracker
	global.__objectDepths[527] = 0; // objMotion_blur
	global.__objectDepths[528] = 0; // obj_antilag
	global.__objectDepths[529] = 0; // obj_hottest
	global.__objectDepths[530] = 0; // obj_none


	global.__objectNames[0] = "obj_globalstart";
	global.__objectNames[1] = "obj_globalstart_escbutton";
	global.__objectNames[2] = "obj_roomcontrol";
	global.__objectNames[3] = "obj_rmcontrol_campaign";
	global.__objectNames[4] = "obj_cam1";
	global.__objectNames[5] = "obj_cam2";
	global.__objectNames[6] = "obj_racestart";
	global.__objectNames[7] = "obj_lapend";
	global.__objectNames[8] = "object1008";
	global.__objectNames[9] = "obj_lapend_nxtrom";
	global.__objectNames[10] = "obj_lapend_rally";
	global.__objectNames[11] = "obj_powerupbox";
	global.__objectNames[12] = "obj_magicdrop";
	global.__objectNames[13] = "obj_wincam_pos";
	global.__objectNames[14] = "obj_falltraparea_hor";
	global.__objectNames[15] = "obj_fall_traparea_vert";
	global.__objectNames[16] = "obj_savepoint";
	global.__objectNames[17] = "obj_jumppad";
	global.__objectNames[18] = "obj_portal_nxtrom";
	global.__objectNames[19] = "obj_portal_prevrom";
	global.__objectNames[20] = "obj_start_sp_pl1";
	global.__objectNames[21] = "obj_start_sp_pl2";
	global.__objectNames[22] = "obj_start_sp_pl3";
	global.__objectNames[23] = "obj_start_sp_pl4";
	global.__objectNames[24] = "obj_start_sp_bot5";
	global.__objectNames[25] = "obj_start_sp_bot6";
	global.__objectNames[26] = "obj_start_custom";
	global.__objectNames[27] = "obj_podium_pos1";
	global.__objectNames[28] = "obj_podium_pos2";
	global.__objectNames[29] = "obj_podium_pos3";
	global.__objectNames[30] = "obj_podium_pos4";
	global.__objectNames[31] = "obj_podium_pos5";
	global.__objectNames[32] = "obj_podium_pos6";
	global.__objectNames[33] = "obj_portal_battle_froggitduo";
	global.__objectNames[34] = "obj_portal_battle_vegeduo";
	global.__objectNames[35] = "obj_portal_battle_vegefrog";
	global.__objectNames[36] = "obj_portal_battle_ruinsmobs";
	global.__objectNames[37] = "obj_portal_battle_snowrally";
	global.__objectNames[38] = "obj_portal_battle_icecapduo";
	global.__objectNames[39] = "obj_portal_battle_snowmobs";
	global.__objectNames[40] = "obj_portal_battle_mk";
	global.__objectNames[41] = "obj_portal_floweyrace";
	global.__objectNames[42] = "obj_portal_blookrace";
	global.__objectNames[43] = "obj_portal_pretorielrace";
	global.__objectNames[44] = "obj_portal_torielrace";
	global.__objectNames[45] = "obj_portal_pretoriel_toruins";
	global.__objectNames[46] = "obj_portal_fake";
	global.__objectNames[47] = "obj_kart_sans";
	global.__objectNames[48] = "obj_kart_papyrus";
	global.__objectNames[49] = "obj_kart_undyne";
	global.__objectNames[50] = "obj_kart_alphys";
	global.__objectNames[51] = "obj_kart_mettaton";
	global.__objectNames[52] = "obj_kart_mttex";
	global.__objectNames[53] = "obj_kart_frisk";
	global.__objectNames[54] = "obj_kart_blook";
	global.__objectNames[55] = "obj_kart_asgore";
	global.__objectNames[56] = "obj_kart_toriel";
	global.__objectNames[57] = "obj_kart_chara";
	global.__objectNames[58] = "obj_kart_asriel";
	global.__objectNames[59] = "obj_kart_gaster";
	global.__objectNames[60] = "obj_kart_flowey";
	global.__objectNames[61] = "obj_kart_muffet";
	global.__objectNames[62] = "obj_kart_maddummy";
	global.__objectNames[63] = "obj_kart_bpants";
	global.__objectNames[64] = "obj_kart_grillby";
	global.__objectNames[65] = "obj_kart_mk";
	global.__objectNames[66] = "obj_kart_tem";
	global.__objectNames[67] = "obj_kart_doggo";
	global.__objectNames[68] = "obj_kart_toby";
	global.__objectNames[69] = "obj_kart_froggit1";
	global.__objectNames[70] = "obj_kart_froggit2";
	global.__objectNames[71] = "obj_kart_vegetoid1";
	global.__objectNames[72] = "obj_kart_vegetoid2";
	global.__objectNames[73] = "obj_kart_snowdrake1";
	global.__objectNames[74] = "obj_kart_snowdrake2";
	global.__objectNames[75] = "obj_kart_icecap1";
	global.__objectNames[76] = "obj_kart_icecap2";
	global.__objectNames[77] = "obj_npc_hfrisk";
	global.__objectNames[78] = "obj_playcpmnbutton";
	global.__objectNames[79] = "obj_playfreebutton";
	global.__objectNames[80] = "obj_menubutton";
	global.__objectNames[81] = "obj_optionsbutton";
	global.__objectNames[82] = "obj_achievebutton";
	global.__objectNames[83] = "obj_exitbutton";
	global.__objectNames[84] = "obj_howmanyplayersbutton";
	global.__objectNames[85] = "obj_botstriggerbutton";
	global.__objectNames[86] = "obj_botsonlybutton";
	global.__objectNames[87] = "obj_readybutton";
	global.__objectNames[88] = "obj_resetbutton";
	global.__objectNames[89] = "obj_laplimitbutton";
	global.__objectNames[90] = "obj_options_renderdist";
	global.__objectNames[91] = "obj_options_musicvol";
	global.__objectNames[92] = "obj_options_controlinput";
	global.__objectNames[93] = "obj_options_controls";
	global.__objectNames[94] = "obj_options_pl1binds_kb";
	global.__objectNames[95] = "obj_options_pl2binds_kb";
	global.__objectNames[96] = "obj_options_pl1_jk";
	global.__objectNames[97] = "obj_options_pl2_jk";
	global.__objectNames[98] = "obj_slct_title";
	global.__objectNames[99] = "obj_slct_papyrus";
	global.__objectNames[100] = "obj_slct_sans";
	global.__objectNames[101] = "obj_slct_undyne";
	global.__objectNames[102] = "obj_slct_alphys";
	global.__objectNames[103] = "obj_slct_frisk";
	global.__objectNames[104] = "obj_slct_mettaton";
	global.__objectNames[105] = "obj_slct_mttex";
	global.__objectNames[106] = "obj_slct_toriel";
	global.__objectNames[107] = "obj_slct_asgore";
	global.__objectNames[108] = "obj_slct_asriel";
	global.__objectNames[109] = "obj_slct_gaster";
	global.__objectNames[110] = "obj_slct_us_sans";
	global.__objectNames[111] = "obj_slct_uf_papy";
	global.__objectNames[112] = "obj_slct_ss_chara";
	global.__objectNames[113] = "obj_slct_flowey";
	global.__objectNames[114] = "obj_slct_napstablook";
	global.__objectNames[115] = "obj_slct_muffet";
	global.__objectNames[116] = "obj_slct_maddummy";
	global.__objectNames[117] = "obj_slct_bpants";
	global.__objectNames[118] = "obj_slct_mk";
	global.__objectNames[119] = "obj_slct_tem";
	global.__objectNames[120] = "obj_slct_grillby";
	global.__objectNames[121] = "obj_slct_toby";
	global.__objectNames[122] = "obj_slct_doggo";
	global.__objectNames[123] = "obj_slct_nochar";
	global.__objectNames[124] = "obj_slctkart_preview";
	global.__objectNames[125] = "obj_achieve_floweysouls";
	global.__objectNames[126] = "obj_achieve_corefall";
	global.__objectNames[127] = "obj_achieve_papyblaster";
	global.__objectNames[128] = "obj_achieve_secretcodewall";
	global.__objectNames[129] = "obj_achieve_unlockdog";
	global.__objectNames[130] = "obj_intro";
	global.__objectNames[131] = "obj_intro_frisk";
	global.__objectNames[132] = "obj_intro_undyne";
	global.__objectNames[133] = "obj_intro_gaster";
	global.__objectNames[134] = "obj_intro_title";
	global.__objectNames[135] = "obj_intro_voidfx";
	global.__objectNames[136] = "obj_menuchar_frisk";
	global.__objectNames[137] = "obj_menuchar_tori";
	global.__objectNames[138] = "obj_menuchar_blook";
	global.__objectNames[139] = "obj_menuchar_vegetoid";
	global.__objectNames[140] = "obj_menuchar_froggit";
	global.__objectNames[141] = "obj_menuchar_gaster";
	global.__objectNames[142] = "obj_menuchar_sans";
	global.__objectNames[143] = "obj_menuchar_papyrus";
	global.__objectNames[144] = "obj_slctchar_ut";
	global.__objectNames[145] = "obj_slctchar_ut_rm1";
	global.__objectNames[146] = "obj_slctchar_ut_rm2";
	global.__objectNames[147] = "obj_slctchar_au";
	global.__objectNames[148] = "obj_lvl_title";
	global.__objectNames[149] = "obj_lvl_ruins";
	global.__objectNames[150] = "obj_lvl_christmas";
	global.__objectNames[151] = "obj_lvl_snowdin_forest";
	global.__objectNames[152] = "obj_lvl_waterfall";
	global.__objectNames[153] = "obj_lvl_core";
	global.__objectNames[154] = "obj_lvl_hotlands";
	global.__objectNames[155] = "obj_lvl_boss_toriel";
	global.__objectNames[156] = "obj_lvl_boss_blook";
	global.__objectNames[157] = "obj_lvl_boss_papyrus";
	global.__objectNames[158] = "obj_newtitle";
	global.__objectNames[159] = "obj_newmenu";
	global.__objectNames[160] = "obj_freerace_vsboss";
	global.__objectNames[161] = "obj_freerace_normalcircuit";
	global.__objectNames[162] = "obj_terspawn_snowdinoverworld";
	global.__objectNames[163] = "obj_terspawn_snowrally";
	global.__objectNames[164] = "obj_terspawn_snowdinmisc";
	global.__objectNames[165] = "obj_terrain_snowdinoverworld";
	global.__objectNames[166] = "obj_terrain_snowrally";
	global.__objectNames[167] = "obj_terrain_snowdinmisc";
	global.__objectNames[168] = "obj_wall_snowdin_hor";
	global.__objectNames[169] = "obj_wall_cliff_horizontal";
	global.__objectNames[170] = "obj_wall_forest_horizontal";
	global.__objectNames[171] = "obj_wall_snowdin_vert";
	global.__objectNames[172] = "obj_wall_cliff_vertical";
	global.__objectNames[173] = "obj_wall_forest_vertical";
	global.__objectNames[174] = "obj_snowcliff_hor";
	global.__objectNames[175] = "obj_snowcliff_vert";
	global.__objectNames[176] = "obj_floor_snowcliff";
	global.__objectNames[177] = "obj_floor_snowdin";
	global.__objectNames[178] = "obj_floor_lowsnow";
	global.__objectNames[179] = "obj_floor_snow";
	global.__objectNames[180] = "obj_snowtile_up";
	global.__objectNames[181] = "obj_snowtilesmallcornersw";
	global.__objectNames[182] = "obj_snowtilelongcornersw";
	global.__objectNames[183] = "obj_snowtilelongcornernw";
	global.__objectNames[184] = "obj_snowtilelongcornerne";
	global.__objectNames[185] = "obj_snowtilelongcornerse";
	global.__objectNames[186] = "obj_snowtilesmallcornernw";
	global.__objectNames[187] = "obj_snowtilesmallcornerne";
	global.__objectNames[188] = "obj_snowtilesmallcornerse";
	global.__objectNames[189] = "obj_snowtile_down";
	global.__objectNames[190] = "obj_snowtile_left";
	global.__objectNames[191] = "obj_snowtile_right";
	global.__objectNames[192] = "obj_floor_forestsnow";
	global.__objectNames[193] = "obj_bridge_horizontal1";
	global.__objectNames[194] = "obj_bridge_horizontal";
	global.__objectNames[195] = "obj_bridge_vertical";
	global.__objectNames[196] = "obj_bridge_horizontal2";
	global.__objectNames[197] = "obj_bridge_vertical1";
	global.__objectNames[198] = "obj_bridge_vertical2";
	global.__objectNames[199] = "obj_floor_ice";
	global.__objectNames[200] = "obj_poff";
	global.__objectNames[201] = "obj_poff_cliff";
	global.__objectNames[202] = "obj_tree";
	global.__objectNames[203] = "obj_tree_cliff";
	global.__objectNames[204] = "obj_doghouse";
	global.__objectNames[205] = "obj_bars";
	global.__objectNames[206] = "obj_npc_politicsbear";
	global.__objectNames[207] = "obj_npc_grillby";
	global.__objectNames[208] = "obj_convenientlamp";
	global.__objectNames[209] = "obj_npc_snowdinlowriders";
	global.__objectNames[210] = "obj_wall_snowbridge_hor";
	global.__objectNames[211] = "obj_wall_snowbridge_vert";
	global.__objectNames[212] = "obj_shop_snowdin";
	global.__objectNames[213] = "obj_inn_snowdin";
	global.__objectNames[214] = "obj_midshop_snowdin";
	global.__objectNames[215] = "obj_librarby";
	global.__objectNames[216] = "obj_grillbys";
	global.__objectNames[217] = "obj_house_snowdin";
	global.__objectNames[218] = "obj_papshouse";
	global.__objectNames[219] = "obj_wall_ruins_hor";
	global.__objectNames[220] = "obj_wall_ruins_vert";
	global.__objectNames[221] = "obj_wall2_ruins_hor";
	global.__objectNames[222] = "obj_wall2_ruins_vert";
	global.__objectNames[223] = "obj_floor_ruins";
	global.__objectNames[224] = "obj_floor_black";
	global.__objectNames[225] = "obj_floor_leaves_ruins";
	global.__objectNames[226] = "obj_floor_vines_ruins";
	global.__objectNames[227] = "obj_floor_trap";
	global.__objectNames[228] = "obj_wall_home_hor";
	global.__objectNames[229] = "obj_wall_home_vert";
	global.__objectNames[230] = "obj_floor_home";
	global.__objectNames[231] = "obj_pillar_ruins";
	global.__objectNames[232] = "obj_home_lamp";
	global.__objectNames[233] = "obj_ruins_tree";
	global.__objectNames[234] = "obj_trap_rock";
	global.__objectNames[235] = "obj_npc_dummy";
	global.__objectNames[236] = "obj_npc_maddummy";
	global.__objectNames[237] = "obj_npc_vegetoid";
	global.__objectNames[238] = "obj_npc_napstablook";
	global.__objectNames[239] = "obj_npc_froggit";
	global.__objectNames[240] = "obj_talkingrock";
	global.__objectNames[241] = "obj_wall_ruins_fake_hor";
	global.__objectNames[242] = "obj_wall_ruins_fake_vert";
	global.__objectNames[243] = "obj_wall_black_hor";
	global.__objectNames[244] = "obj_black_smallwall_hor";
	global.__objectNames[245] = "obj_black_filler";
	global.__objectNames[246] = "obj_wall_black_vert";
	global.__objectNames[247] = "obj_black_smallwall_vert";
	global.__objectNames[248] = "obj_ruinsgate_empty";
	global.__objectNames[249] = "obj_ruinsgate";
	global.__objectNames[250] = "obj_floor_ruins_waterfloor";
	global.__objectNames[251] = "obj_ruins_firstroom";
	global.__objectNames[252] = "obj_ruins_homewalls_vert";
	global.__objectNames[253] = "obj_codewall_hor";
	global.__objectNames[254] = "obj_wall_wfall_hor";
	global.__objectNames[255] = "obj_wall_wfall_vert";
	global.__objectNames[256] = "obj_wall_wfall2_hor";
	global.__objectNames[257] = "obj_wall_wfall2_vert";
	global.__objectNames[258] = "obj_wall_wfall_water_hor";
	global.__objectNames[259] = "obj_wall_wfall_water_vert";
	global.__objectNames[260] = "obj_floor_wfall";
	global.__objectNames[261] = "obj_floor_wfall_grass";
	global.__objectNames[262] = "obj_floor_wfall_waterfloor";
	global.__objectNames[263] = "obj_floor_bridge";
	global.__objectNames[264] = "obj_floor_wfallcliff";
	global.__objectNames[265] = "obj_wfall_cliff_hor";
	global.__objectNames[266] = "obj_wfall_cliff_vert";
	global.__objectNames[267] = "obj_pillar_waterfall";
	global.__objectNames[268] = "obj_prop_bigshroom_wfall";
	global.__objectNames[269] = "obj_prop_mushroom";
	global.__objectNames[270] = "obj_prop_lamp";
	global.__objectNames[271] = "obj_watergate";
	global.__objectNames[272] = "obj_terrain_hotlava";
	global.__objectNames[273] = "obj_hotcliff_hor";
	global.__objectNames[274] = "obj_hotcliff_vert";
	global.__objectNames[275] = "obj_hotlands_floor";
	global.__objectNames[276] = "obj_hotlands_floorpipe_h1";
	global.__objectNames[277] = "obj_hotlands_floorpipe_h2";
	global.__objectNames[278] = "obj_hotlands_floorpipe_v1";
	global.__objectNames[279] = "obj_hotlands_floorpipe_v2";
	global.__objectNames[280] = "obj_hotlands_floorpipe_v3";
	global.__objectNames[281] = "obj_hotlands_pipe";
	global.__objectNames[282] = "obj_floor_corehole";
	global.__objectNames[283] = "obj_floor_core";
	global.__objectNames[284] = "obj_floor_corebridge";
	global.__objectNames[285] = "obj_floor_mttshow";
	global.__objectNames[286] = "obj_wall_core_hor";
	global.__objectNames[287] = "obj_wall_core_vert";
	global.__objectNames[288] = "obj_wall_mttshow_hor";
	global.__objectNames[289] = "obj_wall_mttshow_vert";
	global.__objectNames[290] = "obj_wall_corehole_hor";
	global.__objectNames[291] = "obj_wall_corehole_vert";
	global.__objectNames[292] = "obj_mttshow_gate";
	global.__objectNames[293] = "obj_wall_corebridge_hor";
	global.__objectNames[294] = "obj_wall_corebrige_vert";
	global.__objectNames[295] = "obj_npc_rg01";
	global.__objectNames[296] = "obj_npc_rg02";
	global.__objectNames[297] = "obj_npc_regnpc";
	global.__objectNames[298] = "obj_npc_tsunderplane";
	global.__objectNames[299] = "obj_npc_darkman";
	global.__objectNames[300] = "obj_npc_vulkin";
	global.__objectNames[301] = "obj_npc_harpy";
	global.__objectNames[302] = "obj_npc_heatsf";
	global.__objectNames[303] = "obj_npc_pyrope";
	global.__objectNames[304] = "obj_firepit";
	global.__objectNames[305] = "obj_tree_christmas";
	global.__objectNames[306] = "obj_cane_christmas";
	global.__objectNames[307] = "obj_present_red";
	global.__objectNames[308] = "obj_present_blue";
	global.__objectNames[309] = "obj_present_maroon";
	global.__objectNames[310] = "obj_snowman_sux";
	global.__objectNames[311] = "obj_snowman_luke";
	global.__objectNames[312] = "obj_snowman_ricky";
	global.__objectNames[313] = "obj_snowman_funny";
	global.__objectNames[314] = "obj_snowman_gravy";
	global.__objectNames[315] = "obj_snowman_luigi";
	global.__objectNames[316] = "obj_snowman_muffin";
	global.__objectNames[317] = "obj_snowman_crash";
	global.__objectNames[318] = "obj_snowman_lucas";
	global.__objectNames[319] = "obj_snowman_brawl";
	global.__objectNames[320] = "obj_snowman_seth";
	global.__objectNames[321] = "obj_tem_christmas";
	global.__objectNames[322] = "obj_magic_christmas";
	global.__objectNames[323] = "obj_powerup_christmas";
	global.__objectNames[324] = "obj_christlights_vert";
	global.__objectNames[325] = "obj_christlights_hor";
	global.__objectNames[326] = "obj_newhome_floor";
	global.__objectNames[327] = "obj_newhome_wall_hor";
	global.__objectNames[328] = "obj_newhome_wall_vert";
	global.__objectNames[329] = "obj_newhome_homewall_hor";
	global.__objectNames[330] = "obj_newhome_homewall_vert";
	global.__objectNames[331] = "obj_newhome_homefloor";
	global.__objectNames[332] = "obj_newhome_lamp";
	global.__objectNames[333] = "obj_newhome_throne";
	global.__objectNames[334] = "obj_newhome_thronet";
	global.__objectNames[335] = "obj_newhome_floor_vines";
	global.__objectNames[336] = "obj_newhome_wall_fake_hor";
	global.__objectNames[337] = "obj_newhome_wall_fake_vert";
	global.__objectNames[338] = "obj_goldenflowers";
	global.__objectNames[339] = "obj_newhome_vines_floor";
	global.__objectNames[340] = "obj_judge_pillar";
	global.__objectNames[341] = "obj_judge_floor1";
	global.__objectNames[342] = "obj_judge_floor2";
	global.__objectNames[343] = "obj_judge_floor1_dark";
	global.__objectNames[344] = "obj_judge_floor2_dark";
	global.__objectNames[345] = "obj_judge_floor1_light";
	global.__objectNames[346] = "obj_judge_floor2_light";
	global.__objectNames[347] = "obj_judge_window_1_hor";
	global.__objectNames[348] = "obj_judge_window_1_vert";
	global.__objectNames[349] = "obj_judge_window_2_hor";
	global.__objectNames[350] = "obj_judge_window_2_vert";
	global.__objectNames[351] = "obj_judge_wall_hor";
	global.__objectNames[352] = "obj_judge_wall_vert";
	global.__objectNames[353] = "obj_judge_wall_dark_hor";
	global.__objectNames[354] = "obj_judge_wall_dark_vert";
	global.__objectNames[355] = "obj_col_basic";
	global.__objectNames[356] = "obj_kart_basic";
	global.__objectNames[357] = "obj_floor_draw_basic";
	global.__objectNames[358] = "obj_floor_draw_animated_basic";
	global.__objectNames[359] = "obj_wall_draw_basic";
	global.__objectNames[360] = "obj_wall_draw_animated_basic";
	global.__objectNames[361] = "obj_wall_draw_nocol";
	global.__objectNames[362] = "obj_podium_basic";
	global.__objectNames[363] = "obj_powerup_basic";
	global.__objectNames[364] = "obj_tpfx";
	global.__objectNames[365] = "obj_bonefx";
	global.__objectNames[366] = "obj_spearfx";
	global.__objectNames[367] = "obj_bulletfx";
	global.__objectNames[368] = "obj_bulletfx_big";
	global.__objectNames[369] = "obj_grassfx";
	global.__objectNames[370] = "obj_racefx";
	global.__objectNames[371] = "obj_snowfloorfx";
	global.__objectNames[372] = "obj_waterfloorfx";
	global.__objectNames[373] = "obj_bynaryfallfx";
	global.__objectNames[374] = "obj_kaster_hands";
	global.__objectNames[375] = "obj_hud1";
	global.__objectNames[376] = "obj_hud2";
	global.__objectNames[377] = "obj_hud_racend";
	global.__objectNames[378] = "obj_hud_black";
	global.__objectNames[379] = "obj_hud_quit";
	global.__objectNames[380] = "obj_hud_save";
	global.__objectNames[381] = "obj_hud_battle";
	global.__objectNames[382] = "obj_hud_achievement";
	global.__objectNames[383] = "obj_hud_campaign";
	global.__objectNames[384] = "obj_hud_quit_campaign";
	global.__objectNames[385] = "obj_hud_pause";
	global.__objectNames[386] = "obj_powerup_spike";
	global.__objectNames[387] = "obj_powerup_tilespear";
	global.__objectNames[388] = "obj_powerup_tileweb";
	global.__objectNames[389] = "obj_powerup_bone";
	global.__objectNames[390] = "obj_powerup_asrielstar";
	global.__objectNames[391] = "obj_powerup_asrielbullet";
	global.__objectNames[392] = "obj_powerup_fireball";
	global.__objectNames[393] = "obj_powerup_bone_blue";
	global.__objectNames[394] = "obj_powerup_knife";
	global.__objectNames[395] = "obj_powerup_cotton";
	global.__objectNames[396] = "obj_powerup_spear";
	global.__objectNames[397] = "obj_powerup_pellet";
	global.__objectNames[398] = "obj_powerup_shock";
	global.__objectNames[399] = "obj_powerup_gb";
	global.__objectNames[400] = "obj_powerup_mttsentry";
	global.__objectNames[401] = "obj_powerup_tear";
	global.__objectNames[402] = "obj_powerup_ylwbullet";
	global.__objectNames[403] = "obj_gblast";
	global.__objectNames[404] = "obj_trap_spikes";
	global.__objectNames[405] = "obj_flowey_intro";
	global.__objectNames[406] = "obj_timeline_menu";
	global.__objectNames[407] = "obj_menu_friskart";
	global.__objectNames[408] = "obj_menu_papykart";
	global.__objectNames[409] = "obj_menu_dreemurkart";
	global.__objectNames[410] = "obj_menu_badtime";
	global.__objectNames[411] = "obj_pellet_cutscene";
	global.__objectNames[412] = "obj_fireball_cutscene";
	global.__objectNames[413] = "obj_binarycutscene";
	global.__objectNames[414] = "obj_hfrisk_laughface";
	global.__objectNames[415] = "obj_dlg_errormsg";
	global.__objectNames[416] = "obj_dlg_introflowey";
	global.__objectNames[417] = "obj_dlg_introflowey2";
	global.__objectNames[418] = "obj_dlg_floweyracetut";
	global.__objectNames[419] = "obj_dlg_floweybossintro";
	global.__objectNames[420] = "obj_dlg_floweyrace_friskwins";
	global.__objectNames[421] = "obj_dlg_floweyrace_friskloses";
	global.__objectNames[422] = "obj_dlg_floweypellets_intro";
	global.__objectNames[423] = "obj_dlg_tori_intro";
	global.__objectNames[424] = "obj_dlg_floweyjudgement";
	global.__objectNames[425] = "obj_dlg_floweyjudgement_end";
	global.__objectNames[426] = "obj_dlg_introhakd";
	global.__objectNames[427] = "obj_dlg_floweyintro_hakd";
	global.__objectNames[428] = "obj_dlg_hfriskintro";
	global.__objectNames[429] = "obj_dlg_ruins_blookyrace1";
	global.__objectNames[430] = "obj_dlg_ruins_blookyrace2";
	global.__objectNames[431] = "obj_dlg_froggit_torielalert";
	global.__objectNames[432] = "obj_froggit_mobracealert";
	global.__objectNames[433] = "obj_dlg_blookbossintro";
	global.__objectNames[434] = "obj_dlg_blookwins";
	global.__objectNames[435] = "obj_dlg_blookloses";
	global.__objectNames[436] = "obj_dlg_vgtoid_rockalert";
	global.__objectNames[437] = "obj_dlg_sorryrock";
	global.__objectNames[438] = "obj_dlg_hiya";
	global.__objectNames[439] = "obj_dlg_torielpreintro";
	global.__objectNames[440] = "obj_dlg_torielbossintro";
	global.__objectNames[441] = "obj_dlg_torielwins";
	global.__objectNames[442] = "obj_dlg_torielloses";
	global.__objectNames[443] = "obj_dlg_torielruinsexit";
	global.__objectNames[444] = "obj_dlg_racestart";
	global.__objectNames[445] = "obj_dlg_racewin";
	global.__objectNames[446] = "obj_dlg_racelose";
	global.__objectNames[447] = "obj_dlg_meetsans";
	global.__objectNames[448] = "obj_dlg_meetsansalt";
	global.__objectNames[449] = "obj_dlg_sansrevealed";
	global.__objectNames[450] = "obj_dlg_sanspap1";
	global.__objectNames[451] = "obj_dlg_sansfrisk1";
	global.__objectNames[452] = "obj_dlg_floweypostruins";
	global.__objectNames[453] = "obj_dlg_snowdinlowriders_1";
	global.__objectNames[454] = "obj_dlg_snowdinlowriders_2";
	global.__objectNames[455] = "obj_dlg_snowdinlowriders_3";
	global.__objectNames[456] = "obj_dlg_hfrisk_snowsecret";
	global.__objectNames[457] = "obj_dlg_whatwasthat";
	global.__objectNames[458] = "obj_dlg_threedots";
	global.__objectNames[459] = "obj_dlg_mk_racestart";
	global.__objectNames[460] = "obj_dlg_raceicecapduo";
	global.__objectNames[461] = "obj_dlg_racemk";
	global.__objectNames[462] = "obj_dlg_raceahead";
	global.__objectNames[463] = "obj_dlg_younohere";
	global.__objectNames[464] = "obj_dlg_doghouse";
	global.__objectNames[465] = "obj_dlg_alwaysfacing";
	global.__objectNames[466] = "obj_dlg_papybossintro";
	global.__objectNames[467] = "obj_dlg_papywins";
	global.__objectNames[468] = "obj_dlg_papyloses";
	global.__objectNames[469] = "obj_dlg_papybridge";
	global.__objectNames[470] = "obj_dlg_papybridge_completed";
	global.__objectNames[471] = "obj_dlg_papygate";
	global.__objectNames[472] = "obj_dlg_sanspapracetip";
	global.__objectNames[473] = "obj_trigger_talkwithchar";
	global.__objectNames[474] = "obj_trigger_floweyintrodialog";
	global.__objectNames[475] = "obj_trigger_floweyracetut";
	global.__objectNames[476] = "obj_trigger_floweypellets_intro";
	global.__objectNames[477] = "obj_trigger_tori_intro";
	global.__objectNames[478] = "obj_trigger_rmhacking";
	global.__objectNames[479] = "obj_trigger_floweyjudgement";
	global.__objectNames[480] = "obj_trigger_floweyjudgement_end";
	global.__objectNames[481] = "obj_trigger_floweysink";
	global.__objectNames[482] = "obj_trigger_introhakd";
	global.__objectNames[483] = "obj_trigger_floweyintro_hakd";
	global.__objectNames[484] = "obj_trigger_hfriskintro";
	global.__objectNames[485] = "obj_trigger_floweypostruins";
	global.__objectNames[486] = "obj_trigger_meetsans";
	global.__objectNames[487] = "obj_trigger_sanspap1";
	global.__objectNames[488] = "obj_trigger_sanstp";
	global.__objectNames[489] = "obj_trigger_sansfrisk1";
	global.__objectNames[490] = "obj_trigger_papbridge";
	global.__objectNames[491] = "obj_trigger_papbridge_completed";
	global.__objectNames[492] = "obj_trigger_papygate";
	global.__objectNames[493] = "obj_trigger_froggitduoend";
	global.__objectNames[494] = "obj_trigger_vegeduoend";
	global.__objectNames[495] = "obj_trigger_vegefrogend";
	global.__objectNames[496] = "obj_trigger_ruinsmobsend";
	global.__objectNames[497] = "obj_trigger_snowdrakerallyend";
	global.__objectNames[498] = "obj_trigger_icecapduo";
	global.__objectNames[499] = "obj_trigger_snowmobs";
	global.__objectNames[500] = "obj_trigger_mk";
	global.__objectNames[501] = "obj_trigger_floweybossintro";
	global.__objectNames[502] = "obj_trigger_floweyracefinale";
	global.__objectNames[503] = "obj_trigger_blookbossintro";
	global.__objectNames[504] = "obj_trigger_blookfinale";
	global.__objectNames[505] = "obj_trigger_torielpreintro";
	global.__objectNames[506] = "obj_trigger_torielbossintro";
	global.__objectNames[507] = "obj_trigger_torielfinale";
	global.__objectNames[508] = "obj_trigger_torielruinsexit";
	global.__objectNames[509] = "obj_trigger_papyrusbossintro";
	global.__objectNames[510] = "obj_trigger_papyrusbossfinale";
	global.__objectNames[511] = "obj_tobdog";
	global.__objectNames[512] = "obj_dokdog";
	global.__objectNames[513] = "obj_bynary_spawner";
	global.__objectNames[514] = "obj_cmpn_indev";
	global.__objectNames[515] = "obj_demoend";
	global.__objectNames[516] = "obj_fadetocampaign";
	global.__objectNames[517] = "obj_fadetosnowdin";
	global.__objectNames[518] = "obj_fadetodemoend";
	global.__objectNames[519] = "obj_mouse_joystick";
	global.__objectNames[520] = "obj_gotolvl_freerace";
	global.__objectNames[521] = "obj_gotolvl_campaign";
	global.__objectNames[522] = "obj_writer";
	global.__objectNames[523] = "obj_escbutton";
	global.__objectNames[524] = "obj_escbutton_3d";
	global.__objectNames[525] = "obj_escbutton_3dcampaign";
	global.__objectNames[526] = "obj_achievement_tracker";
	global.__objectNames[527] = "objMotion_blur";
	global.__objectNames[528] = "obj_antilag";
	global.__objectNames[529] = "obj_hottest";
	global.__objectNames[530] = "obj_none";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
