function scr_load_data() {
	//Campaign
	if file_exists("save.ini")
	{
	file=file_text_open_read("save.ini")
	global.gold=file_text_read_real(file)  
	file_text_readln(file) 
	global.startroom=file_text_read_string(file)// Room set when game starts
	file_text_readln(file) 
	global.cmpn_room=file_text_read_real(file)// Current room in campaign
	file_text_readln(file) 
	global.cmpn_times=file_text_read_real(file)// How many times campaign was completed
	file_text_readln(file) 
	global.cmpn_floweyintro=file_text_read_real(file)  
	file_text_readln(file) 
	global.battle_froggitduo=file_text_read_real(file)  
	file_text_readln(file) 
	global.battle_vegeduo=file_text_read_real(file) 
	file_text_readln(file)  
	global.battle_vegefrog=file_text_read_real(file)  
	file_text_readln(file)  
	global.battle_ruinsmobs=file_text_read_real(file)
	file_text_readln(file)  
	global.achieve_floweysouls=file_text_read_real(file)  
	file_text_readln(file) 
	global.achieve_corefall=file_text_read_real(file)  
	file_text_readln(file) 
	global.achieve_secretcodewall=file_text_read_real(file)
	file_text_readln(file) 
	global.achieve_papyblaster=file_text_read_real(file)
	file_text_readln(file) 
	global.unlock_asriel=file_text_read_real(file)  
	file_text_readln(file) 
	global.unlock_gaster=file_text_read_real(file)  
	file_text_readln(file) 
	global.unlock_us_sans=file_text_read_real(file)  
	file_text_readln(file)
	global.unlock_uf_papy=file_text_read_real(file) 
	file_text_readln(file) 
	global.unlock_dog=file_text_read_real(file)  
	file_text_readln(file) 
	global.unlock_toriel=file_text_read_real(file) 
	file_text_readln(file) 
	global.unlock_blook=file_text_read_real(file)  
	file_text_readln(file) 
	global.unlock_ss_chara=file_text_read_real(file) 
	file_text_readln(file) 
	global.renderdistance=file_text_read_real(file)  
	file_text_readln(file) 
	global.musicvolume=file_text_read_real(file)  
	file_text_readln(file) 
	global.controlinput=file_text_read_real(file)  
	file_text_readln(file) 
	global.lighting=file_text_read_real(file)  
	file_text_readln(file) 
	global.lighting_quantity=file_text_read_real(file)  
	file_text_readln(file) 
	global.cmpn_posx=file_text_read_real(file)  
	file_text_readln(file) 
	global.cmpn_posy=file_text_read_real(file) 
	file_text_readln(file) 
	global.cmpn_dir=file_text_read_real(file) 
	file_text_readln(file) 
	global.snowdincutscenefinal=file_text_read_real(file) 
	file_text_readln(file) 
	global.battle_snowdrakerally=file_text_read_real(file) 
	file_text_readln(file) 
	global.battle_icecapduo=file_text_read_real(file) 
	file_text_readln(file) 
	global.battle_snowmobs=file_text_read_real(file) 
	file_text_readln(file) 
	global.battle_mk=file_text_read_real(file) 
	file_text_readln(file) 
	global.unlock_papybossrace=file_text_read_real(file) 
	file_text_readln(file) 
	global.papybridgecutscene=file_text_read_real(file) 
	file_text_close(file)
	}
	else
	{
	global.gold=0
	global.startroom="Spoiler"
	global.cmpn_room=rm_cmpgn_tutorial1
	global.cmpn_times=1
	global.cmpn_floweyintro=0
	global.battle_froggitduo=0
	global.battle_vegeduo=0
	global.battle_vegefrog=0
	global.battle_ruinsmobs=0
	global.achieve_floweysouls=0
	global.achieve_corefall=0
	global.achieve_secretcodewall=0
	global.achieve_papyblaster=0
	global.unlock_asriel=false
	global.unlock_gaster=false
	global.unlock_us_sans=false
	global.unlock_uf_papy=false
	global.unlock_dog=false
	global.unlock_toriel=false
	global.unlock_blook=false
	global.unlock_ss_chara=false
	global.renderdistance=640
	global.musicvolume=1
	global.controlinput=0
	global.lighting=false
	global.lighting_quantity=64
	global.cmpn_posx=112
	global.cmpn_posy=272
	global.cmpn_dir=0
	global.snowdincutscenefinal=false
	global.battle_snowdrakerally=false
	global.battle_icecapduo=false
	global.battle_snowmobs=false
	global.battle_mk=false
	global.unlock_papybossrace=false
	global.papybridgecutscene=false
	}

	//Controls
	if file_exists("controls.ini")
	{
	file=file_text_open_read("controls.ini")
	//Player 1 Keyboard
	global.control_pl1move_kb=file_text_read_real(file)  
	file_text_readln(file) 
	global.control_pl1break_kb=file_text_read_real(file)  
	file_text_readln(file) 
	global.control_pl1right_kb=file_text_read_real(file)  
	file_text_readln(file) 
	global.control_pl1left_kb=file_text_read_real(file)  
	file_text_readln(file) 
	global.control_pl1use_kb=file_text_read_real(file)  
	file_text_readln(file) 
	global.control_pl1special_kb=file_text_read_real(file)  
	file_text_readln(file) 
	global.control_pl1cam_kb=file_text_read_real(file) 
	file_text_readln(file) 
	//Player 2 Keyboard
	global.control_pl2move_kb=file_text_read_real(file)  
	file_text_readln(file) 
	global.control_pl2break_kb=file_text_read_real(file)  
	file_text_readln(file) 
	global.control_pl2right_kb=file_text_read_real(file)  
	file_text_readln(file) 
	global.control_pl2left_kb=file_text_read_real(file)  
	file_text_readln(file) 
	global.control_pl2use_kb=file_text_read_real(file)  
	file_text_readln(file) 
	global.control_pl2special_kb=file_text_read_real(file)  
	file_text_readln(file) 
	global.control_pl2cam_kb=file_text_read_real(file)  
	file_text_readln(file) 
	//Player 1 Joystick
	global.control_pl1move_jk=file_text_read_real(file)  
	file_text_readln(file) 
	global.control_pl1break_jk=file_text_read_real(file)  
	file_text_readln(file) 
	global.control_pl1right_jk=file_text_read_real(file)  
	file_text_readln(file) 
	global.control_pl1left_jk=file_text_read_real(file)  
	file_text_readln(file) 
	global.control_pl1use_jk=file_text_read_real(file)  
	file_text_readln(file) 
	global.control_pl1special_jk=file_text_read_real(file)  
	file_text_readln(file) 
	global.control_pl1cam_jk=file_text_read_real(file) 
	file_text_readln(file) 
	//Player 2 Joystick
	global.control_pl2move_jk=file_text_read_real(file)  
	file_text_readln(file) 
	global.control_pl2break_jk=file_text_read_real(file)  
	file_text_readln(file) 
	global.control_pl2right_jk=file_text_read_real(file)  
	file_text_readln(file) 
	global.control_pl2left_jk=file_text_read_real(file)  
	file_text_readln(file) 
	global.control_pl2use_jk=file_text_read_real(file)  
	file_text_readln(file) 
	global.control_pl2special_jk=file_text_read_real(file)  
	file_text_readln(file) 
	global.control_pl2cam_jk=file_text_read_real(file)  
	file_text_close(file)
	}
	else
	{
	//Global controls for all players (Keyboard)
	global.control_pl1move_kb=ord("W")
	global.control_pl1break_kb=ord("S")
	global.control_pl1right_kb=ord("D")
	global.control_pl1left_kb=ord("A")
	global.control_pl1use_kb=ord("Z")
	global.control_pl1special_kb=ord("X")
	global.control_pl1cam_kb=ord("Q")

	global.control_pl2move_kb=ord("I")
	global.control_pl2break_kb=ord("K")
	global.control_pl2right_kb=ord("L")
	global.control_pl2left_kb=ord("J")
	global.control_pl2use_kb=ord("N")
	global.control_pl2special_kb=ord("M")
	global.control_pl2cam_kb=ord("U")

	//Global controls for all players (Joystick)
	global.control_pl1move_jk=15
	global.control_pl1break_jk=16
	global.control_pl1right_jk=12
	global.control_pl1left_jk=11
	global.control_pl1use_jk=gp_face1
	global.control_pl1special_jk=gp_face2
	global.control_pl1cam_jk=gp_face4

	global.control_pl2move_jk=15
	global.control_pl2break_jk=16
	global.control_pl2right_jk=12
	global.control_pl2left_jk=11
	global.control_pl2use_jk=1
	global.control_pl2special_jk=2
	global.control_pl2cam_jk=4
	}



}
