sndpath="sounds\"

//Soundtrack
global.snd_intro=sound_add(sndpath+"intro.mp3",1,1)
global.snd_menu=sound_add(sndpath+"menu.mp3",1,1)
global.snd_flowey=sound_add(sndpath+"flowey.mp3",1,1)
global.snd_ruins=sound_add(sndpath+"ruins.mp3",1,1)
global.snd_blook=sound_add(sndpath+"blook.mp3",1,1)
global.snd_toriel=sound_add(sndpath+"toriel.mp3",1,1)
global.snd_snowdin=sound_add(sndpath+"snowdin.mp3",1,1)
global.snd_snowdog=sound_add(sndpath+"snowdog.mp3",1,1)
global.snd_waterfall=sound_add(sndpath+"waterfall.mp3",1,1)
global.snd_core=sound_add(sndpath+"core.mp3",1,1)
global.snd_victory=sound_add(sndpath+"victory.mp3",1,1)
global.snd_sans=sound_add(sndpath+"sans.mp3",1,1)
global.snd_papyrus=sound_add(sndpath+"papyrus.mp3",1,1)
global.snd_snowdincircuit=sound_add(sndpath+"snowdincircuit.mp3",1,1)

//Misc Sound FX
global.snd_power_alphys=sound_add(sndpath+"power_alphys.wav",0,1)
global.snd_power_asgore=sound_add(sndpath+"power_asgore.wav",0,1)
global.snd_power_asriel=sound_add(sndpath+"power_asriel.wav",0,1)
global.snd_power_chara=sound_add(sndpath+"power_chara.wav",0,1)
global.snd_power_flowey=sound_add(sndpath+"power_flowey.wav",0,1)
global.snd_power_frisk=sound_add(sndpath+"power_frisk.wav",0,1)
global.snd_power_gaster=sound_add(sndpath+"power_gaster.wav",0,1)
global.snd_power_mtt=sound_add(sndpath+"power_mtt.wav",0,1)
global.snd_power_papyrus=sound_add(sndpath+"power_papyrus.wav",0,1)
global.snd_power_sans=sound_add(sndpath+"power_sans.wav",0,1)
global.snd_power_toriel=sound_add(sndpath+"power_toriel.wav",0,1)
global.snd_power_undyne=sound_add(sndpath+"power_undyne.wav",0,1)
global.snd_power_blook=sound_add(sndpath+"power_blook.wav",0,1)
global.snd_power_muffet=sound_add(sndpath+"power_muffet.wav",0,1)
global.snd_power_mad=sound_add(sndpath+"power_mad.wav",0,1)
