myfont=argument0; // variable font
mycolor=argument1; // variable color
writingx = argument2; //top left x coord
writingy = argument3; //top left y coord
writingxend = argument4; //right boundingbox
shake=argument5; //amount of text shaking
textspeed=argument6; //rate of text parse
txtsound=argument7; //what default sound
spacing=argument8; //text spacing
vspacing=argument9; //vertical spacing yep, old default was 25
